# Generated by Django 5.2.4 on 2025-07-19 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_week', models.CharField(help_text='Comma-separated list of days (e.g., Mon,Tue,Wed)', max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('count_runs', models.IntegerField(default=0)),
                ('ai_model', models.CharField(blank=True, choices=[('gemini-2.5-flash', 'GEMINI_2_5_FLASH'), ('gemini-2.0-flash-lite', 'GEMINI_2_0_FLASH_LITE'), ('gemini-2.0-flash', 'GEMINI_2_0_FLASH'), ('gemini-2.5-flash-lite-preview-06-17', 'GEMINI_2_5_FLASH_LITE_PREVIEW_06_17'), ('gemini-2.0-flash-preview-image-generation', 'GEMINI_2_0_FLASH_PREVIEW_IMAGE_GENERATION')], help_text='Which model will be using by default for these tasks', max_length=255, null=True)),
                ('project_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_schedules', to='github_integration.projecttheme')),
            ],
        ),
    ]
