# Generated by Django 5.2.4 on 2025-07-19 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github_integration', '0001_initial'),
        ('schedule_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIStateBlobs',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('data', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIStateDefault',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('data', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIStateStorage',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('data', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIStateWrites',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('data', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIAgentTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('DONE', 'Done'), ('RUNNING', 'Running'), ('PENDING', 'Pending'), ('ERROR', 'Error'), ('CANCELLED', 'Cancelled')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('ai_model', models.CharField(blank=True, choices=[('gemini-2.5-flash', 'GEMINI_2_5_FLASH'), ('gemini-2.0-flash-lite', 'GEMINI_2_0_FLASH_LITE'), ('gemini-2.0-flash', 'GEMINI_2_0_FLASH'), ('gemini-2.5-flash-lite-preview-06-17', 'GEMINI_2_5_FLASH_LITE_PREVIEW_06_17'), ('gemini-2.0-flash-preview-image-generation', 'GEMINI_2_0_FLASH_PREVIEW_IMAGE_GENERATION')], max_length=255, null=True)),
                ('activity_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule_service.activityschedule')),
                ('project_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='github_integration.projecttheme')),
            ],
        ),
    ]
