# Generated by Django 5.2.4 on 2025-07-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='github_email',
            field=models.CharField(default='***', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='github_username',
            field=models.CharField(default='***', max_length=255),
            preserve_default=False,
        ),
    ]
